### ISSUE TITLE
Env var empty string?

### ISSUE THREAD

**Issue by donquixote** [grasmash/expander#9]
I am using this package in a scenario where some variables are empty strings.
Unfortunately these variables will not be replaced.

The reason is here,
https://github.com/grasmash/expander/blob/master/src/Expander.php#L279

```php
            if (getenv($env_key)) {
                $data->set($property_name, getenv($env_key));
            }
```

The correct value to check against would be `false`.

```php
            if (getenv($env_key) !== false) {
                $data->set($property_name, getenv($env_key));
            }
```

Unfortunately this won't be backwards compatible, if some dependents expect the non-replacement..
Not sure what's the way forward here. For now I just want to report it.

**Comment by greg-1-anderson** [comment]
The `getenv` in the block above was replaced with the code below:
```
            if (isset($_ENV[$env_key])) {
              $data->set($property_name, $_ENV[$env_key]);
            }
```
Unfortunately, `$_ENV` is often empty, as it is only populated if the php.ini setting `variables_order` contains "E". This configuration option is often missing in default php configurations. Using `$_SERVER` would be safer.
